#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint
#npm test
#npm version patch
npm run version
git add package.json src/serviceWorker.js
NODE_VERSION=$(node -p -e "require('./package.json').version")
git commit -m $NODE_VERSION
